/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Article/': RouteRecordInfo<'/Article/', '/Article', Record<never, never>, Record<never, never>>,
    '/Article/[id]': RouteRecordInfo<'/Article/[id]', '/Article/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Auth/Login': RouteRecordInfo<'/Auth/Login', '/Auth/Login', Record<never, never>, Record<never, never>>,
    '/Auth/Register': RouteRecordInfo<'/Auth/Register', '/Auth/Register', Record<never, never>, Record<never, never>>,
    '/Category/': RouteRecordInfo<'/Category/', '/Category', Record<never, never>, Record<never, never>>,
    '/Comment/': RouteRecordInfo<'/Comment/', '/Comment', Record<never, never>, Record<never, never>>,
  }
}
